### PR TITLE
return neovim

### PR DESCRIPTION
**Pull request by TheOrangeCat**

### CODE REVIEW

**Comment by protonesso** [comment]
No, test it

**Comment by TheOrangeCat** [comment]
its the same as your version

**Comment by protonesso** [comment]
If you will not test it I will not merge it

**Comment by TheOrangeCat** [comment]
do i have to compile this s(hit?

**Comment by protonesso** [comment]
Yes, you must or no merge

**Comment by TheOrangeCat** [comment]
>>> Installing package: 'm4'
 * Checking for file conflicts
 * Following files couldn't be overwritten
usr/share/info/dir
 * Failed to emerge package

**Comment by protonesso** [comment]
Under Ataraxia environment

**Comment by TheOrangeCat** [comment]
im compiling ataraxia you know

**Comment by protonesso** [comment]
If you were compiling under Ataraxia there shouldn't be m5 dependency

**Comment by TheOrangeCat** [comment]
HOW CAN I COMPILE ATARAXIA UNDER ATARAXIA IF I CANT COMPILE ATARAXIA

**Comment by TheOrangeCat** [comment]
u dum s(het

**Comment by protonesso** [comment]
Wait I'm testing patch for kagami

**Comment by protonesso** [comment]
Reinstall kagami. You don't need to recompile Ataraxia from scratch

**Comment by TheOrangeCat** [comment]
i dont have ataraxia you know

**Comment by protonesso** [comment]
recompile your HOST kagami (and who calls me dumb?)

**Comment by TheOrangeCat** [comment]
still not work
plus remove i486 from supported arch list cuz it isnt supported

**Comment by protonesso** [comment]
Thanks for reminding me, use i586 instead of i486

**Comment by protonesso** [comment]
Did you git pull and ./build -B && ./build -I?

**Comment by TheOrangeCat** [comment]
yes

**Comment by TheOrangeCat** [comment]
except not git pull
its tmpfs

**Comment by TheOrangeCat** [comment]
so git clone

**Comment by protonesso** [comment]
I have m4 compiled

**Comment by TheOrangeCat** [comment]
i cant test it
i get kernel panic when trying to boot from instcd

**Comment by protonesso** [comment]
How much memory did you allocate?

**Comment by TheOrangeCat** [comment]
256 meg

**Comment by protonesso** [comment]
Try 512

**Comment by protonesso** [comment]
fixed in my private repo

**Pull request closed without merging**
