### PR TITLE
added kot-pkg

### PR DESCRIPTION
**Pull request by TheOrangeCat**

### CODE REVIEW

**Comment by protonesso** [comment]
why

**Comment by TheOrangeCat** [comment]
because you need to have alternatives

**Comment by protonesso** [comment]
It's incompatible with Ataraxia

**Comment by TheOrangeCat** [comment]
why?

**Comment by protonesso** [comment]
i should ask you. why?

**Comment by TheOrangeCat** [comment]
> because you need to have alternatives

**Comment by TheOrangeCat** [comment]
you shouldnt even care. its a community repo

**Comment by TheOrangeCat** [comment]
@protonesso

**Comment by TheOrangeCat** [comment]
> there are no releases
> installing shit in its own folder is better
> installing binaries in usr is useless in my case
> there is no post-install
> its a community repo
> im going to protest

**Comment by protonesso** [comment]
i don't care then

**Pull request closed without merging**
